create table roles
(
    id          int8 generated by default as identity,
    description varchar,
    name        varchar,

    primary key (id)
);

create table users
(
    id          int8 generated by default as identity,
    username    varchar,
    email       varchar,
    first_name  varchar,
    second_name varchar,
    password    varchar,
    blocked     boolean,
    role_id     int8 not null,

    primary key (id),
    foreign key (role_id) references roles
);


