create table meets
(
    id          int8 generated by default as identity,
    name        varchar,
    date        date,
    start_time  time,
    end_time    time,
    link        varchar,
    description varchar,
    creator_id  int8,

    primary key (id),
    foreign key (creator_id) references public.users(id)
);

create table guest_status
(
    id     int8 generated by default as identity,
    status varchar,

    primary key (id)
);

create table meet_guests
(
    id        int8 generated by default as identity,
    meet_id   int8,
    guest_id  int8,
    status_id int8,

    primary key (id),
    foreign key (guest_id) references public.users(id),
    foreign key (meet_id) references meets(id),
    foreign key (status_id) references guest_status(id)
);
